"use strict";

/**
 * @file dictionary.js
 * @brief Trained part vocabulary ({@link PartDictionary}) plus its text and
 * binary serialization.
 *
 * Port of `core/parts/dictionary.cpp` + `dict_io.cpp`.
 *
 * A {@link PartDictionary} stores the trained part vocabulary: it is built
 * once by the extractor, then queried read-only by the decomposer. A part's
 * identity is the pair `(kind, value)` (see {@link Kind}); insertion order is
 * the part's ID.
 *
 * Serialization stores **every part at its real id** (including the single-char
 * atoms) so part ids are stable across save → load — a fresh build inserts some
 * atoms early (e.g. the Whole `"a"`), so regenerating them at load would renumber
 * everything. Only **Delimiters** are omitted and regenerated by
 * {@link augmentWithAtoms} at load (they are a fixed manual set, the sole
 * exception). The text form ({@link saveDictText} / {@link loadDictText}) writes
 * one value per line using the position-marker convention, with a trailing
 * `[delim]` section. The marker *position* carries the {@link Kind} (leading =
 * End, trailing = Start, both = Mid, none = Whole) and the marker *glyph* carries
 * the **track provenance** — `"__"` for discriminative parts, `"##"` for
 * generative / untagged — so the `tracks` map is rebuilt on load (no side-car
 * `.tracks.json`). The binary form ({@link saveDictBinary} /
 * {@link loadDictBinary}) writes a `"BDI2"` header followed by
 * `(u8 kind, u16 len, bytes)` records, where the kind byte's high bit is the
 * discriminative flag. Both loaders attach the rebuilt map as `dict.tracks`. All
 * values are byte-strings (see `byteString.js`).
 *
 * **Exported surface:**
 * - `PartDictionary` — the vocabulary container.
 * - `augmentWithAtoms(dict)` — seed the deterministic singleton/special atoms.
 * - `saveDictText(dict)` / `loadDictText(text)` — text IO (atoms included).
 * - `saveDictBinary(dict)` / `loadDictBinary(bytes)` — binary IO (atoms included).
 *
 * @see {@link Kind}
 */

import { Kind, kInvalidPartId } from "./kind.js";

// Connector characters seeded by augmentWithAtoms / excluded from files.
const CONNECTORS = ["-", ",", ".", "$"];
const CONNECTOR_CODES = new Set(CONNECTORS.map((c) => c.charCodeAt(0)));

/**
 * @constant DELIMITERS
 * @description The fixed, code-defined delimiter atom set — NOT learned from any
 * corpus. Contains the four normalized whitespace forms, the two normalized
 * punctuation runs (`"..."`, `"--"`), and every single ASCII punctuation byte.
 * Any delimiter the tokenizer emits resolves against these either as a whole
 * match or char-by-char; non-ASCII (mojibake) bytes are simply dropped during
 * decomposition, so they never enter the dictionary. Regenerated at load by
 * {@link augmentWithAtoms}, so — like the single-char atoms — delimiters are
 * excluded from serialized files.
 * @type {string[]}
 */
export const DELIMITERS = (() => {
  const out = [" ", "\t", "\n", "\n\n", "...", "--"];
  for (const [lo, hi] of [
    [33, 47], // ! " # $ % & ' ( ) * + , - . /
    [58, 64], // : ; < = > ? @
    [91, 96], // [ \ ] ^ _ `
    [123, 126], // { | } ~
  ]) {
    for (let c = lo; c <= hi; c++) out.push(String.fromCharCode(c));
  }
  return out;
})();

/**
 * @function keyOf
 * @description Builds the composite map key that uniquely identifies a
 * `(kind, value)` part. The {@link Kind} numeric value is encoded as a single
 * leading UTF-16 code unit (via `String.fromCharCode`) and the byte-string
 * `value` is appended verbatim, so the same value under a different kind yields
 * a distinct key. Used by {@link PartDictionary} as the key of its
 * `_keyToId` map.
 * @param {number} kind - A {@link Kind} value (used as a character code).
 * @param {string} value - The part value as a byte-string.
 * @returns {string} The composite key: the kind character followed by `value`.
 *
 * @example
 * // Kind.Whole === 4, so the key is String.fromCharCode(4) + "the":
 * keyOf(Kind.Whole, "the")   // → String.fromCharCode(4) + "the"
 */
const keyOf = (kind, value) => String.fromCharCode(kind) + value;

/**
 * @class PartDictionary
 * @description The trained part vocabulary. Each entry is keyed by its
 * `(kind, value)` pair, and its insertion index is the stable part ID. Adding
 * the same `(kind, value)` twice is a no-op that returns the original ID, so
 * IDs never shift once assigned. Values are byte-strings (see `byteString.js`).
 *
 * A dictionary is built once by the extractor (via repeated {@link PartDictionary#add}
 * calls), then queried read-only by the decomposer through {@link PartDictionary#lookup}
 * and the `has*` predicates. Note that identity is on the pair: the same value
 * under a different {@link Kind} is a distinct part with its own ID.
 *
 * @example
 * const dict = new PartDictionary();
 * const the = dict.add(Kind.Whole, "the");   // → 0  (first part, ID 0)
 * dict.add(Kind.Whole, "the");               // → 0  (dedups: same ID)
 * dict.add(Kind.Start, "the");               // → 1  (distinct kind, new ID)
 * dict.size();                               // → 2
 * dict.lookup(Kind.Whole, "the");            // → 0
 * dict.lookup(Kind.Whole, "missing");        // → kInvalidPartId
 * dict.hasWhole("the");                      // → true
 * dict.hasStart("the");                      // → true
 * dict.hasStart("missing");                  // → false
 */
export class PartDictionary {
  constructor() {
    /** @type {Array<{kind: number, value: string}>} */
    this._idToKey = [];
    /** @type {Map<string, number>} */
    this._keyToId = new Map();
  }

  /**
   * @method add
   * @description Adds a `(kind, value)` part, or returns the existing ID if the
   * pair is already present. IDs are assigned in insertion order and never
   * change, so this is safe to call repeatedly while building the vocabulary.
   * @param {number} kind - A {@link Kind} value.
   * @param {string} value - The part value as a byte-string.
   * @returns {number} The part ID (newly assigned, or the existing one).
   *
   * @example
   * const dict = new PartDictionary();
   * dict.add(Kind.Whole, "the");   // → 0
   * dict.add(Kind.Whole, "the");   // → 0  (already present, deduped)
   * dict.add(Kind.End, "ing");     // → 1
   */
  add(kind, value) {
    const k = keyOf(kind, value);
    const existing = this._keyToId.get(k);
    if (existing !== undefined) return existing;
    const id = this._idToKey.length;
    this._idToKey.push({ kind, value });
    this._keyToId.set(k, id);
    return id;
  }

  /**
   * @method lookup
   * @description Returns the ID of the `(kind, value)` part, or
   * {@link kInvalidPartId} if it is not in the dictionary.
   * @param {number} kind - A {@link Kind} value.
   * @param {string} value - The part value as a byte-string.
   * @returns {number} The part ID, or `kInvalidPartId` when absent.
   *
   * @example
   * const dict = new PartDictionary();
   * dict.add(Kind.Whole, "the");
   * dict.lookup(Kind.Whole, "the");     // → 0
   * dict.lookup(Kind.Whole, "missing"); // → kInvalidPartId
   * dict.lookup(Kind.Start, "the");     // → kInvalidPartId  (kind differs)
   */
  lookup(kind, value) {
    const id = this._keyToId.get(keyOf(kind, value));
    return id === undefined ? kInvalidPartId : id;
  }

  /**
   * @method at
   * @description Returns the `(kind, value)` entry stored at the given part ID,
   * or `undefined` if the ID is out of range.
   * @param {number} id - A part ID (as returned by {@link PartDictionary#add}).
   * @returns {{ kind: number, value: string } | undefined} The entry, or
   *   `undefined` when the ID is not present.
   *
   * @example
   * const dict = new PartDictionary();
   * dict.add(Kind.Whole, "the");
   * dict.at(0);   // → { kind: Kind.Whole, value: "the" }
   * dict.at(99);  // → undefined
   */
  at(id) {
    return this._idToKey[id];
  }

  /**
   * @method size
   * @description Returns the number of parts in the dictionary.
   * @returns {number} The part count (also the ID that the next {@link PartDictionary#add}
   *   would assign).
   *
   * @example
   * const dict = new PartDictionary();
   * dict.size();                 // → 0
   * dict.add(Kind.Whole, "the");
   * dict.size();                 // → 1
   */
  size() {
    return this._idToKey.length;
  }

  /**
   * @method countOfKind
   * @description Counts how many parts in the dictionary have the given
   * {@link Kind}.
   * @param {number} kind - A {@link Kind} value.
   * @returns {number} The number of parts of that kind.
   *
   * @example
   * const dict = new PartDictionary();
   * augmentWithAtoms(dict);
   * dict.countOfKind(Kind.Whole);      // → 40
   * dict.countOfKind(Kind.Mid);        // → 40
   * dict.countOfKind(Kind.Delimiter);  // → 38
   */
  countOfKind(kind) {
    let n = 0;
    for (const k of this._idToKey) if (k.kind === kind) n++;
    return n;
  }

  /**
   * @method allParts
   * @description Returns the backing array of `(kind, value)` entries in ID
   * order. The array is returned by reference (not a copy) — treat it as
   * read-only. Used by the serializers to iterate the vocabulary.
   * @returns {Array<{ kind: number, value: string }>} Parts in ID order.
   *
   * @example
   * const dict = new PartDictionary();
   * dict.add(Kind.Whole, "the");
   * dict.add(Kind.End, "ing");
   * dict.allParts();
   * // → [{ kind: Kind.Whole, value: "the" }, { kind: Kind.End, value: "ing" }]
   */
  allParts() {
    return this._idToKey;
  }

  /**
   * @method hasStart
   * @description Returns `true` if a {@link Kind.Start} part with the given
   * value is in the dictionary.
   * @param {string} value - The part value as a byte-string.
   * @returns {boolean}
   *
   * @example
   * const dict = new PartDictionary();
   * dict.add(Kind.Start, "un");
   * dict.hasStart("un");   // → true
   * dict.hasStart("re");   // → false
   */
  hasStart(value) {
    return this.lookup(Kind.Start, value) !== kInvalidPartId;
  }

  /**
   * @method hasEnd
   * @description Returns `true` if a {@link Kind.End} part with the given value
   * is in the dictionary.
   * @param {string} value - The part value as a byte-string.
   * @returns {boolean}
   *
   * @example
   * const dict = new PartDictionary();
   * dict.add(Kind.End, "ing");
   * dict.hasEnd("ing");   // → true
   * dict.hasEnd("ed");    // → false
   */
  hasEnd(value) {
    return this.lookup(Kind.End, value) !== kInvalidPartId;
  }

  /**
   * @method hasMid
   * @description Returns `true` if a {@link Kind.Mid} part with the given value
   * is in the dictionary.
   * @param {string} value - The part value as a byte-string.
   * @returns {boolean}
   *
   * @example
   * const dict = new PartDictionary();
   * dict.add(Kind.Mid, "port");
   * dict.hasMid("port");    // → true
   * dict.hasMid("graph");   // → false
   */
  hasMid(value) {
    return this.lookup(Kind.Mid, value) !== kInvalidPartId;
  }

  /**
   * @method hasWhole
   * @description Returns `true` if a {@link Kind.Whole} part with the given
   * value is in the dictionary.
   * @param {string} value - The part value as a byte-string.
   * @returns {boolean}
   *
   * @example
   * const dict = new PartDictionary();
   * dict.add(Kind.Whole, "the");
   * dict.hasWhole("the");   // → true
   * dict.hasWhole("am");    // → false
   */
  hasWhole(value) {
    return this.lookup(Kind.Whole, value) !== kInvalidPartId;
  }

  /**
   * @method hasDelimiter
   * @description Returns `true` if a {@link Kind.Delimiter} part with the given
   * value is in the dictionary.
   * @param {string} value - The part value as a byte-string.
   * @returns {boolean}
   *
   * @example
   * const dict = new PartDictionary();
   * augmentWithAtoms(dict);
   * dict.hasDelimiter("-");   // → true
   * dict.hasDelimiter("?");   // → false
   */
  hasDelimiter(value) {
    return this.lookup(Kind.Delimiter, value) !== kInvalidPartId;
  }
}

// ---- Augment set membership ----------------------------------------------

/**
 * @function isConnectorValue
 * @description Returns `true` if `value` is exactly one of the six connector
 * characters (`- ' & , . $`). Used to detect the connector atoms that
 * {@link augmentWithAtoms} regenerates and the serializers therefore omit.
 * @param {string} value - The part value as a byte-string.
 * @returns {boolean} `true` if `value` is a single connector character.
 */
const isConnectorValue = (value) => value.length === 1 && CONNECTOR_CODES.has(value.charCodeAt(0));

/**
 * @function isAugmented
 * @description Returns `true` if the given part is one that
 * {@link augmentWithAtoms} would regenerate deterministically at load, and so
 * must be omitted from serialized files. Matches:
 * - every length-1 {@link Kind.Start}/{@link Kind.Mid}/{@link Kind.End} part
 *   (the positional single-char atoms — learned parts are always length ≥ 2);
 * - single-character {@link Kind.Whole} atoms in `a`–`z`, `0`–`9`, or the
 *   connectors;
 * - every {@link Kind.Delimiter} part (the fixed manual {@link DELIMITERS} set).
 * @param {{ kind: number, value: string }} part - A `(kind, value)` entry.
 * @returns {boolean} `true` if the part is an augment atom (excluded from IO).
 */
const isAugmented = ({ kind, value }) => {
  if (value.length === 1 && (kind === Kind.Start || kind === Kind.Mid || kind === Kind.End)) return true;
  if (kind === Kind.Whole && value.length === 1) {
    const c = value.charCodeAt(0);
    if (c >= 97 && c <= 122) return true; // a-z
    if (c >= 48 && c <= 57) return true; // 0-9
    if (isConnectorValue(value)) return true;
  }
  if (kind === Kind.Delimiter) return true; // all delimiters are manual atoms
  return false;
};

/**
 * @function augmentWithAtoms
 * @description Regenerates the deterministic singleton/special atoms that the
 * serializers omit from files, adding them into `dict` in place:
 * - single-char {@link Kind.Whole} atoms for `a`–`z`, `0`–`9`, and the six
 *   connectors (`- ' & , . $`);
 * - the three positional length-1 fragments — {@link Kind.Start} (`s`),
 *   {@link Kind.Mid} (`s`), {@link Kind.End} (`s`) — for each of those same 40
 *   characters (bare value; position is the kind);
 * - the fixed manual {@link DELIMITERS} set.
 *
 * Because {@link PartDictionary#add} dedups, this is idempotent and safe to run
 * on an already-populated dictionary — it only fills in any missing atoms. This
 * is invoked automatically at the end of {@link loadDictText} and
 * {@link loadDictBinary}.
 * @param {PartDictionary} dict - The dictionary to seed, mutated in place.
 * @returns {void}
 *
 * @example
 * const dict = new PartDictionary();
 * augmentWithAtoms(dict);
 * dict.countOfKind(Kind.Whole);       // → 40   (26 letters + 10 digits + 4 connectors)
 * dict.countOfKind(Kind.Mid);         // → 40   (one length-1 Mid per char)
 * dict.countOfKind(Kind.Delimiter);   // → 38   (manual DELIMITERS set)
 * dict.lookup(Kind.Start, "a");       // not kInvalidPartId
 */
export const augmentWithAtoms = (dict) => {
  /**
   * @function addLetterPositions
   * @description Adds the three positional length-1 fragment atoms for a single
   * character `s` into the enclosing `dict`: word-start ({@link Kind.Start}),
   * word-interior ({@link Kind.Mid}), and word-end ({@link Kind.End}). The value
   * is the bare character — position is carried by the kind. Relies on
   * {@link PartDictionary#add} deduping, so it is idempotent.
   * @param {string} s - The single character to seed positional fragments for.
   * @returns {void}
   *
   * @example
   * addLetterPositions("a");
   * // adds Kind.Start "a", Kind.Mid "a", Kind.End "a"
   */
  const addLetterPositions = (s) => {
    dict.add(Kind.Start, s);
    dict.add(Kind.Mid, s);
    dict.add(Kind.End, s);
  };
  for (let c = 97; c <= 122; c++) dict.add(Kind.Whole, String.fromCharCode(c));
  for (let c = 48; c <= 57; c++) dict.add(Kind.Whole, String.fromCharCode(c));
  for (const c of CONNECTORS) dict.add(Kind.Whole, c);

  for (let c = 97; c <= 122; c++) addLetterPositions(String.fromCharCode(c));
  for (let c = 48; c <= 57; c++) addLetterPositions(String.fromCharCode(c));
  for (const c of CONNECTORS) addLetterPositions(c);

  for (const d of DELIMITERS) dict.add(Kind.Delimiter, d);
};

// ---- Text escape / unescape (for delimiter values) -----------------------

/**
 * @function escapeValue
 * @description Encodes a delimiter value into the text-file escape form so it can
 * be written as a single line in the `[delim]` section. The escaping is:
 * newline → `\n`, tab → `\t`, carriage return → `\r`, backslash → `\\`, and any
 * other control byte (`< 0x20` or `0x7f`) → `\xHH` (two uppercase hex digits).
 * All other bytes are passed through unchanged. This is the inverse of
 * {@link unescapeValue}.
 * @param {string} s - The delimiter value as a byte-string.
 * @returns {string} The escaped, single-line-safe representation.
 *
 * @example
 * escapeValue("a\tb")   // → "a\\tb"    (a real tab becomes the two chars \t)
 * escapeValue("\x00")   // → "\\x00"   (NUL becomes the four chars \x00)
 * escapeValue("a b")    // → "a b"     (printable bytes unchanged)
 */
const escapeValue = (s) => {
  let out = "";
  for (let i = 0; i < s.length; i++) {
    const c = s.charCodeAt(i);
    if (c === 10) out += "\\n";
    else if (c === 9) out += "\\t";
    else if (c === 13) out += "\\r";
    else if (c === 92) out += "\\\\";
    else if (c < 0x20 || c === 0x7f) {
      out += "\\x" + c.toString(16).toUpperCase().padStart(2, "0");
    } else out += s[i];
  }
  return out;
};

/**
 * @function hexDigit
 * @description Converts a single hexadecimal ASCII character code into its
 * numeric value `0`–`15`, or `-1` if the code is not a hex digit. Accepts
 * `0`–`9`, lowercase `a`–`f`, and uppercase `A`–`F`. Used by
 * {@link unescapeValue} to decode `\xHH` escapes.
 * @param {number} c - A character code (as from `charCodeAt`).
 * @returns {number} The digit value `0`–`15`, or `-1` if `c` is not a hex digit.
 *
 * @example
 * hexDigit("7".charCodeAt(0))   // → 7
 * hexDigit("a".charCodeAt(0))   // → 10
 * hexDigit("F".charCodeAt(0))   // → 15
 * hexDigit("z".charCodeAt(0))   // → -1
 */
const hexDigit = (c) => {
  if (c >= 48 && c <= 57) return c - 48;
  if (c >= 97 && c <= 102) return c - 97 + 10;
  if (c >= 65 && c <= 70) return c - 65 + 10;
  return -1;
};

/**
 * @function unescapeValue
 * @description Decodes a delimiter value from the text-file escape form back into
 * its raw byte-string, inverting {@link escapeValue}. Recognizes `\n`, `\t`,
 * `\r`, `\\`, and `\xHH` (two hex digits via {@link hexDigit}). A backslash that
 * does not begin a recognized escape — including a trailing backslash or a
 * malformed `\xHH` — is emitted literally and parsing continues at the next
 * character.
 * @param {string} s - The escaped, single-line delimiter representation.
 * @returns {string} The decoded raw value as a byte-string.
 *
 * @example
 * unescapeValue("a\\tb")   // → "a\tb"   (the two chars \t become a real tab)
 * unescapeValue("\\x41")   // → "A"      (\x41 decodes to byte 0x41)
 * unescapeValue("a\\")     // → "a\\"    (dangling backslash kept literally)
 */
const unescapeValue = (s) => {
  let out = "";
  for (let i = 0; i < s.length; ) {
    if (s.charCodeAt(i) !== 92) {
      out += s[i++];
      continue;
    }
    if (i + 1 >= s.length) {
      out += "\\";
      i++;
      continue;
    }
    const esc = s.charCodeAt(i + 1);
    if (esc === 110) {
      out += "\n";
      i += 2;
    } else if (esc === 116) {
      out += "\t";
      i += 2;
    } else if (esc === 114) {
      out += "\r";
      i += 2;
    } else if (esc === 92) {
      out += "\\";
      i += 2;
    } else if (esc === 120) {
      // \xHH
      if (i + 3 < s.length) {
        const h = hexDigit(s.charCodeAt(i + 2));
        const l = hexDigit(s.charCodeAt(i + 3));
        if (h >= 0 && l >= 0) {
          out += String.fromCharCode((h << 4) | l);
          i += 4;
          continue;
        }
      }
      out += "\\";
      i++;
    } else {
      out += "\\";
      i++;
    }
  }
  return out;
};

/**
 * @function startsWithHashHash
 * @description Returns `true` if `s` begins with the `"##"` position marker.
 * @param {string} s - The line/value to test.
 * @returns {boolean} `true` if the first two characters are `#` and `#`.
 */
const startsWithHashHash = (s) => s.length >= 2 && s.charCodeAt(0) === 35 && s.charCodeAt(1) === 35;

/**
 * @function endsWithHashHash
 * @description Returns `true` if `s` ends with the `"##"` position marker.
 * @param {string} s - The line/value to test.
 * @returns {boolean} `true` if the last two characters are `#` and `#`.
 */
const endsWithHashHash = (s) =>
  s.length >= 2 && s.charCodeAt(s.length - 2) === 35 && s.charCodeAt(s.length - 1) === 35;

/**
 * @function markerAt
 * @description Returns the two-character position marker at offset `i` — `"##"`
 * (generative / untagged) or `"__"` (discriminative) — or `null` if neither is
 * present. The marker *glyph* carries the part's track provenance; its *position*
 * (leading / trailing) carries the {@link Kind}. Values never contain `#` or `_`
 * (not word characters), so a marker is always unambiguous.
 * @param {string} s - The line to inspect.
 * @param {number} i - Offset of the two-char marker.
 * @returns {"##"|"__"|null} The marker glyph, or `null`.
 */
const markerAt = (s, i) => {
  if (i < 0 || i + 2 > s.length) return null;
  const a = s.charCodeAt(i), b = s.charCodeAt(i + 1);
  if (a === 35 && b === 35) return "##"; // "##" — generative / untagged
  if (a === 95 && b === 95) return "__"; // "__" — discriminative
  return null;
};

// ---- Text IO -------------------------------------------------------------

/**
 * @function saveDictText
 * @description Serializes a dictionary to the text format. Every Whole/Start/Mid/End
 * part is written in ID order (including the single-char atoms — see the file
 * header on id stability), using the position-marker convention where the glyph
 * encodes provenance (`"__"` discriminative, `"##"` otherwise), followed by a
 * `[delim]` section marker. Only Delimiters are omitted (regenerated at load).
 * Returns a byte-string; write it to disk as latin1 to reproduce the C++ bytes
 * exactly.
 * @param {PartDictionary} dict - The dictionary to serialize.
 * @param {Object<string, string>} [tracks=dict.tracks||{}] - Map `"kind|value"` →
 *   `"d"`/`"g"`/`"w"`; only `"d"` entries get the `"__"` glyph. Defaults to the
 *   map carried on `dict.tracks` (set by `generateParts` / the loaders).
 * @returns {string} The serialized text as a byte-string.
 *
 * @example
 * const dict = new PartDictionary();
 * dict.add(Kind.Whole, "the");
 * dict.add(Kind.Start, "un");
 * dict.add(Kind.End, "ing");
 * dict.add(Kind.Mid, "port");
 * saveDictText(dict);
 * // → "the\nun##\n##ing\n##port##\n[delim]\n"
 */
export const saveDictText = (dict, tracks = dict.tracks || {}) => {
  let out = "";
  // Pass 1: Whole / Start / Mid / End in ID order — ALL of them, including the
  // single-char atoms. Writing every part at its real id keeps ids STABLE across
  // save → load (a fresh build inserts some atoms early, e.g. the whole "a", so
  // regenerating them at load would renumber everything). Only Delimiters are
  // regenerated (they fall through the switch default and are never written).
  // The marker GLYPH carries provenance: "__" for discriminative parts, "##" for
  // everything else (generative / untagged backstop). Wholes carry no marker.
  for (const k of dict.allParts()) {
    const g = tracks[k.kind + "|" + k.value] === "d" ? "__" : "##";
    switch (k.kind) {
      case Kind.Whole:
        out += k.value + "\n";
        break;
      case Kind.Start:
        out += k.value + g + "\n";
        break;
      case Kind.Mid:
        out += g + k.value + g + "\n";
        break;
      case Kind.End:
        out += g + k.value + "\n";
        break;
      default:
        break; // Delimiter handled below; length-1 atoms filtered above
    }
  }
  // Pass 2: Delimiter section.
  out += "[delim]\n";
  for (const k of dict.allParts()) {
    if (k.kind !== Kind.Delimiter) continue;
    if (isAugmented(k)) continue;
    out += escapeValue(k.value) + "\n";
  }
  return out;
};

/**
 * @function loadDictText
 * @description Parses the text format produced by {@link saveDictText} into a new
 * {@link PartDictionary} — parts are added in file order so ids match the source
 * dictionary — then calls {@link augmentWithAtoms}, which regenerates the omitted
 * Delimiters (the atoms it also adds are already present, so they dedup to a no-op).
 * Blank lines are skipped and trailing `\r` (CRLF) is tolerated; the `[delim]`
 * marker switches parsing into the delimiter section. Read the file as latin1
 * so the bytes match the C++ output exactly. The `tracks` map is rebuilt from the
 * marker glyph (`"__"` → `"d"`, `"##"` → `"g"`, wholes → `"w"`) and attached as
 * `dict.tracks`.
 * @param {string} text - The serialized text as a byte-string.
 * @returns {PartDictionary} A dictionary containing the parsed parts plus the
 *   regenerated atoms, with the rebuilt provenance map on `dict.tracks`.
 *
 * @example
 * const dict = loadDictText("the\nun##\n__ing\n[delim]\n");
 * dict.hasWhole("the");        // → true
 * dict.hasStart("un");         // → true   ("##" → generative)
 * dict.hasEnd("ing");          // → true
 * dict.tracks[Kind.End + "|ing"]; // → "d" ("__" → discriminative)
 * dict.hasWhole("a");          // → true  (restored by augmentWithAtoms)
 */
export const loadDictText = (text) => {
  const dict = new PartDictionary();
  const tracks = {};
  // Rebuild the track map from the marker glyph: "__" → discriminative, "##" →
  // generative. Only length ≥ 2 affixes carry a track (matching the generator);
  // single-char atoms stay untagged. Wholes are always "w".
  const tag = (kind, value, disc) => { if (value.length >= 2) tracks[kind + "|" + value] = disc ? "d" : "g"; };
  let inDelim = false;
  for (let line of text.split("\n")) {
    while (line.length > 0 && line.charCodeAt(line.length - 1) === 13) {
      line = line.slice(0, -1);
    }
    if (line.length === 0) continue;
    if (line === "[delim]") {
      inDelim = true;
      continue;
    }
    if (inDelim) {
      dict.add(Kind.Delimiter, unescapeValue(line));
      continue;
    }
    const s = markerAt(line, 0);
    const e = markerAt(line, line.length - 2);
    if (s && e) {
      const v = line.slice(2, line.length - 2);
      if (v.length > 0) { dict.add(Kind.Mid, v); tag(Kind.Mid, v, s === "__"); }
    } else if (e) {
      const v = line.slice(0, line.length - 2);
      dict.add(Kind.Start, v); tag(Kind.Start, v, e === "__");
    } else if (s) {
      const v = line.slice(2);
      dict.add(Kind.End, v); tag(Kind.End, v, s === "__");
    } else {
      dict.add(Kind.Whole, line);
      if (line.length >= 2) tracks[Kind.Whole + "|" + line] = "w";
    }
  }
  augmentWithAtoms(dict);
  dict.tracks = tracks;
  return dict;
};

// ---- Binary IO (BDI2) ----------------------------------------------------

const MAGIC_BDI2 = [0x42, 0x44, 0x49, 0x32]; // "BDI2"
const BINARY_VERSION = 1;

/**
 * @function saveDictBinary
 * @description Serializes a dictionary to the binary `BDI2` format:
 * a `"BDI2"` magic, a version byte, three reserved bytes, then one
 * `(u8 kind, u16 length LE, value bytes)` record per part in ID order (atoms
 * included, for id stability). Only Delimiters are omitted (regenerated at load).
 * Throws if a
 * part value is longer than `0xffff` bytes.
 * @param {PartDictionary} dict - The dictionary to serialize.
 * @returns {Uint8Array} The encoded byte buffer.
 *
 * @example
 * const dict = new PartDictionary();
 * dict.add(Kind.Whole, "hi");
 * const bytes = saveDictBinary(dict);
 * // First four bytes are the "BDI2" magic:
 * Array.from(bytes.slice(0, 4));   // → [0x42, 0x44, 0x49, 0x32]
 * // Round-trips back to the same trained parts:
 * loadDictBinary(bytes).hasWhole("hi");   // → true
 */
export const saveDictBinary = (dict, tracks = dict.tracks || {}) => {
  const bytes = [...MAGIC_BDI2, BINARY_VERSION, 0, 0, 0]; // header: magic + ver + reserved u8 + reserved u16
  for (const k of dict.allParts()) {
    if (k.kind === Kind.Delimiter) continue; // only Delimiters are regenerated at load; atoms are written for id stability
    const len = k.value.length;
    if (len > 0xffff) throw new Error("part value exceeds uint16 length");
    const disc = tracks[k.kind + "|" + k.value] === "d";
    bytes.push(k.kind | (disc ? 0x80 : 0)); // low bits = Kind (Start0..Whole4); high bit = discriminative track
    bytes.push(len & 0xff, (len >> 8) & 0xff); // u16 LE
    for (let i = 0; i < len; i++) bytes.push(k.value.charCodeAt(i) & 0xff);
  }
  return Uint8Array.from(bytes);
};

/**
 * @function loadDictBinary
 * @description Parses the binary `BDI2` format produced by {@link saveDictBinary}
 * into a new {@link PartDictionary} — records added in order so ids match the
 * source — then calls {@link augmentWithAtoms}, which regenerates the omitted
 * Delimiters (its atom adds dedup to no-ops).
 * Throws on a bad magic, an unsupported version, an out-of-range kind byte, or
 * a truncated record.
 * @param {Uint8Array} bytes - The encoded byte buffer.
 * @returns {PartDictionary} A dictionary containing the parsed parts plus the
 *   regenerated atoms.
 * @throws {Error} If the magic is not `"BDI2"`, the version is unsupported, a
 *   kind byte exceeds `5`, or a record is truncated.
 *
 * @example
 * const dict = new PartDictionary();
 * dict.add(Kind.Whole, "hi");
 * const reloaded = loadDictBinary(saveDictBinary(dict));
 * reloaded.hasWhole("hi");   // → true
 * reloaded.hasWhole("a");    // → true  (restored by augmentWithAtoms)
 *
 * @example
 * loadDictBinary(Uint8Array.from([1, 2, 3, 4, 5, 6, 7, 8]));
 * // → throws Error: loadDictBinary: bad magic (expected BDI2)
 */
export const loadDictBinary = (bytes) => {
  if (
    bytes.length < 8 ||
    bytes[0] !== MAGIC_BDI2[0] ||
    bytes[1] !== MAGIC_BDI2[1] ||
    bytes[2] !== MAGIC_BDI2[2] ||
    bytes[3] !== MAGIC_BDI2[3]
  ) {
    throw new Error("loadDictBinary: bad magic (expected BDI2)");
  }
  const version = bytes[4];
  if (version !== BINARY_VERSION) {
    throw new Error("loadDictBinary: unsupported version " + version);
  }
  // bytes[5] reserved u8, bytes[6..7] reserved u16.

  const dict = new PartDictionary();
  const tracks = {};
  let p = 8;
  while (p < bytes.length) {
    const kb = bytes[p++]; // clean EOF if p was already == length
    const disc = (kb & 0x80) !== 0;
    const kind = kb & 0x7f; // strip the discriminative-track high bit
    if (kind > 4) throw new Error("loadDictBinary: bad kind byte");
    if (p + 2 > bytes.length) throw new Error("loadDictBinary: truncated length");
    const len = bytes[p] | (bytes[p + 1] << 8);
    p += 2;
    if (p + len > bytes.length) throw new Error("loadDictBinary: truncated value");
    let value = "";
    for (let i = 0; i < len; i++) value += String.fromCharCode(bytes[p + i]);
    p += len;
    dict.add(kind, value);
    if (value.length >= 2) tracks[kind + "|" + value] = kind === Kind.Whole ? "w" : disc ? "d" : "g";
  }
  augmentWithAtoms(dict);
  dict.tracks = tracks;
  return dict;
};

/**
 * @ignore
 */
export default PartDictionary;